"use strict";

export const cities = [
    "Stockholm",
    "Göteborg",
    "Malmö",
    "Uppsala",
    "Linköping",
    "Västerås",
    "Örebro",
    "Helsingborg",
    "Norrköping",
    "Jönköping",
    "Umeå",
    "Lund",
    "Borås",
    "Sundsvall",
    "Eskilstuna",
    "Gävle",
    "Södertälje",
    "Karlstad",
    "Täby",
    "Växjö",
    "Halmstad",
    "Luleå",
    "Trelleborg",
    "Östersund",
    "Karlskrona",
    "Kalmar",
    "Skövde",
    "Karlskoga",
    "Kristianstad",
    "Nyköping",
    "Falun"
]
